spring:
  datasource:
    url: jdbc:mysql://localhost:3306/permission?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
#    password: 123456
    port: 6379
    database: 8
server:
  port: 8080